# Generated by Django 3.1.4 on 2021-01-01 07:08

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.TextField(default='')),
                ('last_name', models.TextField(default='')),
                ('phone_number', models.TextField(null=True)),
                ('email', models.TextField(primary_key=True, serialize=False)),
                ('password', models.TextField()),
                ('user_id', models.TextField(null=True, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('user_type', models.IntegerField(default=1)),
                ('device_token', models.TextField(null=True)),
                ('profile_picture_url', models.TextField(null=True)),
                ('profile_picture_id', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
